sleep with fail

diff --git a/guestbook/sleep.yaml b/guestbook/sleep.yaml
--- a/guestbook/sleep.yaml
+++ b/guestbook/sleep.yaml
@@ -1,15 +1,22 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: pre-sync-job
+  name: delayed-fail
   annotations:
     argocd.argoproj.io/hook: PreSync
-    argocd.argoproj.io/hook-delete-policy: HookSucceeded
 spec:
+  backoffLimit: 0
   template:
     spec:
       containers:
-        - name: sleep
+        - name: delayed-fail
           image: busybox
-          command: ["sleep", "30"]  # Sleep for 30 seconds
+          command:
+            - /bin/sh
+            - -c
+            - |
+              echo "Waiting 30 seconds before failing..."
+              sleep 30
+              echo "Now failing the sync"
+              exit 1
       restartPolicy: Never
